brew "gh"
brew "git"
brew "mas"
brew "pinentry-mac"
brew "starship"

cask "1password"
cask "firefox@developer-edition"
cask "flux"
cask "google-chrome"
cask "hiddenbar"
cask "imageoptim"
cask "kap"
cask "rectangle"
cask "visual-studio-code"
