alias cob="git checkout -b "      # Create and switch to a new git branch.
alias com="git checkout main"     # Switch to the 'main' git branch.
alias dev="cd ~/Developer"        # Change directory to ~/Developer.
alias gap="git add -p"            # Interactively add changes to git.
alias gp="git pull"               # Pull latest changes from git remote.
alias gs="git status"             # Show git status.
alias gsp="git stash pop"         # Pop the latest git stash.
alias gst="git stash -u && gs"    # Stash all changes (including untracked), then show git status.
alias gundo="git reset HEAD~"     # Undo the last git commit, keeping changes staged.
alias reload="exec zsh"           # Reload the current zsh shell.
alias upgrade="zsh ~/.config/upgrade.zsh"  # Run upgrade script for zsh configuration.
